# This file defines various watering profiles and can be edited by the user.
# When editing, only change things that follow a colon.  Things before the 
# colons are variable names that the program assumes are defined. Things 
# that come after the colons are the values of the variables.
# No tab characters allowed, use only spaces.
#
# This file can contain any number of profiles.  One profile is set to active
# the others MUST be set to inactive.  The active profile at startup will be
# set to the one marked active in this file but can be changed via the sap 
# (Set Active Profile) command.
#
# Profiles can be viewed (listed) via the 'lp' (List Profiles) command.
# Actice profiles can be chnged (set) via th 'sap' (Set Active Profile) cmd.
#
# The last profile herein is a comprehensive profile example with comments
# a wise person will read this example carefully before editing this file.
############################################
profile0:
  about:       Just relay 1, 3 times per day for 1 min.
  active:      True
  relay1:
    About:     Back Yard Mstr Bed Side 
    Days:      [all]
    Times:     [830]
    durations: [1.5]
  #relay2:
  #  About:     Back Yard Spa Side 
  #  Days:      [None]
  #  Times:     [None]
  #  durations: [None]
  #relay3:
  #  About:     Hill Below Driveway 
  #  Days:      [None]
  #  Times:     [None]
  #  durations: [None]
  #relay4:
  #  About:     Hill Above Driveway 
  #  Days:      [None]
  #  Times:     [None]
  #  durations: [None]
  #relay5:
  #  About:     Front Yard Planter Strip 
  #  Days:      [None]
  #  Times:     [None]
  #  durations: [None]
  #relay6:
  #  About:     NC - 24V Ready 
  #  Days:      [None]
  #  Times:     [None]
  #  durations: [None]
  #relay7:
  #  About:     NC
  #  Days:      [None]
  #  Times:     [None]
  #  durations: [None]
  #relay8:
  #  About:     NC
  #  Days:      [None]
  #  Times:     [None]
  #  durations: [None]
############################################
profile1:
  active:      False
  about:       A comprehensive example profile.
  #relay1:
  #  About:     Describe which sprinkler this relay is connected to.
  #  Days:      [even]          # Legal values: even, odd, all or a
  #                             # list-of-specific-days.
  #
  #  Times:     [910,1030,1105] # Time(s) of day the relay will close.
  #                             # 24-hour military time format HHMM or HMM. No leading zeros.
  #
  #  durations: [1,2,3]         # How long the relay will be closed. Units = minutes. 
  #                             # Decimals ok, i.e. 1.5 = 90 seconds.  
  #                             # Number of 'Times' must equal number of 'durations'.  
  #                             # The first duration corresponds to hte first Time, etc.
  #relay2:
  #  About:     Describe which sprinkler this relay is connected to.
  #  Days:      [odd]
  #  Times:     [1800,1801]     # These periods overlap, that's ok.
  #  durations: [1.5,1]         # Handled as on @ 1800 off at 1702. Relay will not glitch.  
  #
  #relay3:
  #  About:     Describe which sprinkler this relay is connected to.
  #  Days:      [Monday,Wednesday,Friday]
  #  Times:     [1433]
  #  durations: [3]
  #
  #relay4:
  #  About:     Describe which sprinkler this relay is connected to.
  #  Days:      [all]
  #  Times:     [1600,1500]     # Times don't need to be in order.
  #  durations: [2,1]
  #
  #relay5:
  #  About:     Describe which sprinkler this relay is connected to.
  #  Days:      [None]
  #  Times:     [None]
  #  durations: [None]
  #
  relay6:
    About:     NC so use to test w/o turning on a sprinkler 
    Days:      [all]
    Times:     [2042,2043,2044]
    durations: [1,.5,1]

  relay7:
    About:     NC so use to test w/o turning on a sprinkler 
    Days:      [Tuesday]
    Times:     [2043,2044,2045]
    durations: [.5,.1,1]

  relay8:
    About:     NC so use to test w/o turning on a sprinkler
    Days:      [odd]
    Times:     [2044,2045,2046]
    durations: [1,2,1]
############################################

